# SPDX-FileCopyrightText: 2021-2025 Fenrir contributors <https://github.com/ForNeVeR/Fenrir>
#
# SPDX-License-Identifier: MIT

name: Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 6
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - id: version
      name: Get version
      shell: pwsh
      run: echo "version=$(scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)" >> $env:GITHUB_OUTPUT

    - name: NuGet cache
      uses: actions/cache@v4
      with:
       path: ${{ env.NUGET_PACKAGES }}
       key: release.nuget.${{ hashFiles('**/*.fsproj') }}

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4

    - name: Read changelog
      uses: ForNeVeR/ChangelogAutomation.action@v2
      with:
        output: ./release-notes.md

    - name: Prepare a NuGet package
      run: dotnet pack ./Fenrir.Git/Fenrir.Git.fsproj --configuration Release -p:Version=${{ steps.version.outputs.version }}

    - name: Publish for all os
      run: |
        dotnet publish ./Fenrir.Application/Fenrir.Application.fsproj --configuration Release --output publish

    - name: Package the application
      run: |
        zip -r Fenrir.Application.${{ steps.version.outputs.version }}.zip ./publish/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |-
          ./release-notes.md
          ./Fenrir.Git/bin/Release/Fenrir.Git.${{ steps.version.outputs.version }}.nupkg
          ./Fenrir.Git/bin/Release/Fenrir.Git.${{ steps.version.outputs.version }}.snupkg
          ./Fenrir.Application.${{ steps.version.outputs.version }}.zip

    - if: startsWith(github.ref, 'refs/tags/v')
      name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        name: Fenrir v${{ steps.version.outputs.version }}
        body_path: ./release-notes.md
        files: |-
          ./Fenrir.Git/bin/Release/Fenrir.Git.${{ steps.version.outputs.version }}.nupkg
          ./Fenrir.Git/bin/Release/Fenrir.Git.${{ steps.version.outputs.version }}.snupkg
          ./Fenrir.Application.${{ steps.version.outputs.version }}.zip

    - if: startsWith(github.ref, 'refs/tags/v')
      name: Push a package to NuGet
      run: dotnet nuget push ./Fenrir.Git/bin/Release/Fenrir.Git.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
